### ISSUE TITLE
Rabo new  CSV Format

### ISSUE THREAD

**Issue by pa4th** [boszkie/gnucash_converter#5]
Hello,

The rabobank has a new csv format from Q1 2018 . With on the first line 

"IBAN/BBAN","Munt","BIC","Volgnr","Datum","Rentedatum","Bedrag","Saldo na trn","Tegenrekening IBAN/BBAN","Naam tegenpartij","Naam uiteindelijke partij","Naam initiërende partij","BIC tegenpartij","Code","Batch ID","Transactiereferentie","Machtigingskenmerk","Incassant ID","Betalingskenmerk","Omschrijving-1","Omschrijving-2","Omschrijving-3","Reden retour","Oorspr bedrag","Oorspr munt","Koers"

**Comment by boszkie** [comment]
Thanks! I will release a new version as soon as I have time. Or feel free to submit a pull request.

**Comment by boszkie** [comment]
Solved in https://github.com/boszkie/gnucash_converter/releases/tag/gnucash_csv_converter-0.3
